name: Aws EC2 Workflow V5

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Deploy to AWS EC2 (example via SSH)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/nest-primsa-swagger || exit 1
            git pull origin main
            npm install
            npm run build
            pm2 restart all
